### ISSUE TITLE
The project file was unloaded

### ISSUE THREAD

**Issue by IsaacHogben** [FrancLo92/Tafe20S104#1]
![image](https://user-images.githubusercontent.com/61402449/77842419-6f74f800-71d9-11ea-89a6-279bcab71177.png)

When trying to load the project it suggests I install missing features.

![image](https://user-images.githubusercontent.com/61402449/77842465-00e46a00-71da-11ea-8a5c-b300bf3dfe40.png)

![image](https://user-images.githubusercontent.com/61402449/77842442-bb27a180-71d9-11ea-932c-10a0163596d5.png)

But installing them doesn't seem to change anything

**Comment by FrancLo92** [comment]
Hi Isaac, the program is running fine on my machine.

Double check your target version is the same as mine. I think that is the problem.
![image](https://user-images.githubusercontent.com/61133277/77842529-ed85ce80-71da-11ea-97f5-b3190615fefb.png)

**Comment by IsaacHogben** [comment]
How do I navigate to this window?

**Comment by FrancLo92** [comment]
Right click onto your project (not the solution) and click on properties.

**Comment by IsaacHogben** [comment]
I'm not sure I can do that when the project is unloaded.
![image](https://user-images.githubusercontent.com/61402449/77843745-bff35200-71e7-11ea-8042-9ac520d8102f.png)

**Comment by FrancLo92** [comment]
Try this.

Go to the project folder and open with notepad the StartFinance.csproj file ( highlited in the screen shot)
![image](https://user-images.githubusercontent.com/61133277/77844200-0480ec80-71ec-11ea-9c5f-168cdc0345ed.png)


Go to line 14 and 15 and change the target version to the one shown in the photo. Save file and try to reopen the project.
![image](https://user-images.githubusercontent.com/61133277/77844221-43af3d80-71ec-11ea-9aad-4c77f8fb2263.png)

**Comment by IsaacHogben** [comment]
Its already set to that version
![image](https://user-images.githubusercontent.com/61402449/77844274-ebc50680-71ec-11ea-95e4-a8fc6a8c3ee5.png)

I think i have to change the target version somewhere in visual studio settings

**Comment by FrancLo92** [comment]
Does it give u an error code? If yes can you provide it please?

**Comment by IsaacHogben** [comment]
No error code, only what was in my first post.

**Comment by oatmael** [comment]
Hi Isaac,
Sorry to be late to the ball on this one. Have you tried reloading the project already?

If that doesn't work, it's possible somehow the solution didn't have any project attached to it. Follow the prompts here and try and add the project back manually.
![image](https://user-images.githubusercontent.com/45870261/78101809-2f5b8280-7430-11ea-822d-df54026a16c3.png)

**Comment by IsaacHogben** [comment]
Reloading the project doesn't work and trying to add existing project results in this..
![image](https://user-images.githubusercontent.com/61402449/78106708-756a1380-743b-11ea-8e72-767cf4fa5a24.png)

**Comment by oatmael** [comment]
perhaps try removing the project and re-adding it in?

**Comment by FrancLo92** [comment]
Hi Isaac after doing some research, from my understanding something went wrong with the SDK installation. What i suggest is:

- Delete the repository
- Delete any existing folder of the SDK 10.0.10240 on your local machine (if it is there)
- Reinstall the SDK on its own , find the one you need from this link https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/
- finally clone the repository and run it.

Let me know how you go with it.

**Comment by IsaacHogben** [comment]
Hi Franc, I tried this out yesterday and didn't have any luck. I do think that it is a problem with visual studio being able to locate SDK 10.0.10240 but i still haven't found a solution. Ill try re-installing vs next.

**Comment by FrancLo92** [comment]
I was hoping for you to come back with good news. Hopefully reinstalling visual studio will work. Please let me know how you go. Talk soon :)

**Comment by IsaacHogben** [comment]
Hi Franc, I tried all the above steps as well as reinstalling visual studio and all related programs. Neither of which worked.

I will continue looking for solutions in the mean time.

**Comment by oatmael** [comment]
Hey @IsaacHogben ,
I had a rather interesting time when attempting to review other branches of the project, and may have stumbled upon a solution. I encountered the exact same problem (with the project being unloaded, which was strange considering it was working for me beforehand.)

Here are the steps I took to resolve this:
1. I uninstalled all Windows SDKs I currently had on my computer.
2. This resulted in the project loading, however obviously it would not compile due to the lack of SDKs.
3. In the Visual Studio installer, I modified my VS 2017 installation so that it would download the UWP SDK.
4. Having redownloaded the SDK, the project was again unloaded. However, this time I could right click the project and click "download update"
5. This downloaded the correct version of the SDK, and allowed the project to load and run as per usual.

I'm unsure whether this solution will work for you, but give it a go and let me know if it works.

**Comment by IsaacHogben** [comment]
Ive been using VS 2015. Should i be using 2017?

**Comment by oatmael** [comment]
Yes, as stupid as it may seem using VS 2017 did resolve my issues when attempting to load the project for the first time (I was using VS 2019).

**Comment by IsaacHogben** [comment]
Ok, I beleive @FrancLo92 has been using 2015. Won't this cause issues later down the track?

**Comment by oatmael** [comment]
So he is, for some reason I was under the assumption that he was using 2017 (not sure where I got that from).
In any case, uninstalling and reinstalling the SDKs may solve the issue. Note that I did this via Windows Add or Remove Programs, and not VS installer.

**Comment by oatmael** [comment]
> Ok, I beleive @FrancLo92 has been using 2015. Won't this cause issues later down the track?

To more specifically answer this question, using 2017 did not give me any problems. Obviously using the same version is ideal for this kind of project, so take my experience with a grain of salt.

**Comment by IsaacHogben** [comment]
I tried uninstalling all SDKs using 'Windows Add or Remove Programs' and then reinstalled SDK 10240 using the modify option for VS 2015 in 'Add or Remove Programs' and this hasn't worked either. VS 2015 just does not recognise that windows SDK 10.0.10240 is installed.
![image](https://user-images.githubusercontent.com/61402449/78468629-dbff7200-7758-11ea-9049-fa997026398b.png)


Im going to try loading the project in VS 2017 next.

**Comment by FrancLo92** [comment]
Hi guys as per usual i thought we were all using VS 2015, however since @oatmael  has solved the issue with VS 2017 we should stick with VS 2017. We should of established the VS version to use from the beginning, i guess this has thought us a good lesson for the future :D . I am going to download VS 2017 and check both the appointment and contact details branch to check if they work. I will give u guys an update as soon as i am finished.
