### ISSUE TITLE
Feat_ContactDetails - Doesn't run

### ISSUE THREAD

**Issue by FrancLo92** [FrancLo92/Tafe20S104#2]
When i try to run Feat_ContactDetails, the program won't start. All i can see is this screen 

![image](https://user-images.githubusercontent.com/61133277/78419611-ea815700-768e-11ea-9793-d68c03701d9d.png)

I don't know if the problem is my machine or the actual code.

I tried to checkout the feat_Appointment branch to see if the program would run and it did so. 

@oatmael  can you please confirm with me that the program on the feat_ContactDetails works on your machine?

Thank you.

**Comment by oatmael** [comment]
All is working fine on my machine, as seen in the following screenshot:

![image](https://user-images.githubusercontent.com/45870261/78419829-0ab21580-7691-11ea-98ed-3e08818fa1e8.png)

Do the logs show anything?

**Comment by FrancLo92** [comment]
Yes the show logs are showing your changes but it doesn't run. 
![image](https://user-images.githubusercontent.com/61133277/78419883-a2afff00-7691-11ea-9efd-262fcd0529a8.png)

Did you install any nu get packages to develop your feature ?

**Comment by FrancLo92** [comment]
@oatmael maybe  try to clone the remote repository onto yor local machine, then, try running appointment branch and contact detail branch. Let me know if they work.

Thank you.

**Comment by oatmael** [comment]
@FrancLo92 I have successfully found the source of the issue and have (hopefully) resolved it.
You can see the details in my last commit to the feat_ContactDetails branch (the issue was due to unloaded files). I will consider the issue closed until further notice.
