### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by IsaacHogben** [FrancLo92/Tafe20S104#5]
When trying to build the project I get these errors...
![image](https://user-images.githubusercontent.com/61402449/78765646-6e0cb200-79c7-11ea-99eb-e867cfbfe3fd.png)

because my visual studio can't find this reference...
![image](https://user-images.githubusercontent.com/61402449/78765756-9694ac00-79c7-11ea-9e4a-5e9b95f854f7.png)

Everything else works but Im getting an error for every use of dialog.ShowAsync.

My research suggested reinstalling VS and all the SDK's which i have tried and it didn't work.

**Comment by IsaacHogben** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'IAsyncAction' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.	Start Finance	G:\StartFinanceRepo\Tafe20S104\StartFinanceMaster\InstaRichie\Views\AssetsPage.xaml.cs	76	Active

**Comment by FrancLo92** [comment]
Hi Isaac, after doing some research i recommend to look at this.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/ca285503-2feb-4f19-9c95-155222ef8a51/uwp-the-type-iasyncaction-is-defined-in-an-assembly-that-is-not-referenced?forum=wpdevelop

https://stackoverflow.com/questions/41943297/iasyncoperation-await-in-windows-service-type-is-defined-in-an-assembly-that-i

I assume you have already cleaned and rebuilt the solution.

By looking at multiple forums, many people solved this exact same issue by uninstalling and reinstalling the SDK. However i think you should make sure you have the right references in place.

**Comment by IsaacHogben** [comment]
Hi Franc

I tried adding those references, i got this error for 3 of them.
![image](https://user-images.githubusercontent.com/61402449/78976354-261b9580-7b55-11ea-9f04-576be13955fe.png)

Which i assume means they were already working.
The 4th reference; C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.md
worked but didn't fix the errors.

**Comment by FrancLo92** [comment]
Hi Isaac,  have you got any update on this issue? Unfortunately other than reinstalling the correct references i don't really know how to fix the issue.

**Comment by IsaacHogben** [comment]
Hi Franc, I tried everything i could find and didnt have any luck.
To avoid wasting more time I have dug up an old laptop and started working with that. Its slow but it seems to be working.
So for now ill close this issue. Thanks for your patients.
