### ISSUE TITLE
Master Branch no longer runs

### ISSUE THREAD

**Issue by IsaacHogben** [FrancLo92/Tafe20S104#7]
@FrancLo92 
The Shell.xaml file has overlapping code from the merge with feat_appointment.
![image](https://user-images.githubusercontent.com/61402449/79682102-d593ee80-825e-11ea-8192-f03fba267a97.png)

**Comment by FrancLo92** [comment]
@IsaacHogben Thanks for letting me know. I have fixed the problem and pushed the changes into the remote repo. I will consider this issue closed.
